Repository jpeterburs/game_of_life, pull requests merged in 2020-06, with the labels that each got.

#4 GitHub Community files
  .github/workflows/compiler.yml
  DOCUMENTATION.md
  LICENSE
  README.md
  game_of_life.pap
  images/.keep
Labels: documentation

#5 add create_field and print_field
  game_of_life.c
  game_of_life.h
  main.c
Labels: enhancement

#19 Setting game rules and Calculating next step
  game_of_life.c
  game_of_life.h
  main.c
Labels: game logic

#20 Fill initial field with random chells
  game_of_life.c
  main.c
Labels: enhancement, game logic

#22 Add create_field back again
  main.c
Labels: bug

#2 Validate input
  game_of_life.c
  game_of_life.h
Labels: enhancement

#24 Add win state determination
  game_of_life.c
  game_of_life.h
  main.c
Labels: game logic

#21 Add header for print_field
  game_of_life.c
  main.c
Labels: design / layout, extras

#23 added save_field
  game_of_life.c
  game_of_life.h
Labels: extras

#25 UI Update
  game_of_life.c
  game_of_life.h
  main.c
Labels: design / layout, enhancement, extras

#26 Import field
  game_of_life.c
  game_of_life.h
Labels: extras

#27 auto mode and usage of save_field, load_field and input_rule_set
  game_of_life.c
  game_of_life.h
Labels: handling

#28 Finishing touches
  .gitignore
  Makefile
  README.md
  bin/.keep
  console_helper.c
  console_helper.h
  game_of_life.c
  game_of_life.h
  game_of_life.pap
  images/.keep
Labels: bug, design / layout, documentation, handling

#37 Validate everything
  DOCUMENTATION.md
  game_of_life.c
  game_of_life.h
Labels: enhancement, extras

#38 Vernünftige Doku
  DOCUMENTATION.md
  README.md
  game_of_life.c
  pap/calculate_next_step.png
  pap/copy_field.png
  pap/create_field.png
  pap/game_of_life.pap
  pap/has_won.png
  pap/input_rule_set.png
  pap/load_field.png
  pap/print_field.png
  pap/save_field.png
  pap/start_game.png
  pap/start_menu.png
  pap/validate_input.png
Labels: design / layout, documentation, extras

#39 Validate file loading and saving
  game_of_life.c
  pap/game_of_life.pap
Labels: documentation, enhancement
